<?php
class MainPageConstants
{
	const MAIN_PAGE_TEMPLATE_PATH = 'code/MainPage/MainPageTemplate.html';
	const TAG_SOURCE_LANGUAGE_REPEATER_ITEM = "SOURCE_LANGUAGE_ITEM";
	const TAG_DESTINATION_LANGUAGE_REPEATER_ITEM = "DESTINATION_LANGUAGE_ITEM";
	const TAG_PAGE_SIZE_REPEATER_ITEM = "PAGE_SIZE_ITEM";
}